// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8IeObwrE7PxY2c7P78nGKUvvNHR5VH6w',
    appId: '1:204664783429:web:3c2fa6522f7c6f82e6d92c',
    messagingSenderId: '204664783429',
    projectId: 'ecommerce-a3216',
    authDomain: 'ecommerce-a3216.firebaseapp.com',
    storageBucket: 'ecommerce-a3216.appspot.com',
    measurementId: 'G-JC4YD1KHF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp3Q50BUR96ivDUeZ9mRKZVQESJlYfvJI',
    appId: '1:204664783429:android:1fbbfb53f83d0d45e6d92c',
    messagingSenderId: '204664783429',
    projectId: 'ecommerce-a3216',
    storageBucket: 'ecommerce-a3216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYnYVeuvkkPSz4Tb6VIC12b5_1GpPGlw',
    appId: '1:204664783429:ios:5984497df19bf8c6e6d92c',
    messagingSenderId: '204664783429',
    projectId: 'ecommerce-a3216',
    storageBucket: 'ecommerce-a3216.appspot.com',
    androidClientId: '204664783429-66t1bc9af4rod6b66bhorgj6u0qajuki.apps.googleusercontent.com',
    iosClientId: '204664783429-m9mgs80i7tmotemcs5k9dkp5vijgh3ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTYnYVeuvkkPSz4Tb6VIC12b5_1GpPGlw',
    appId: '1:204664783429:ios:6351b48942b0b1f3e6d92c',
    messagingSenderId: '204664783429',
    projectId: 'ecommerce-a3216',
    storageBucket: 'ecommerce-a3216.appspot.com',
    androidClientId: '204664783429-66t1bc9af4rod6b66bhorgj6u0qajuki.apps.googleusercontent.com',
    iosClientId: '204664783429-4tvlhbme0bh5ts499vm05v9cvslf3mva.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdmin.RunnerTests',
  );
}
